-- ============================================================================
-- Validation and Monitoring Tables Setup
-- ============================================================================
-- Creates tables for tracking pipeline runs, validation results, and logs
-- ============================================================================

USE DATABASE DATA_PIPELINE_DB;
USE SCHEMA VALIDATION;

-- Pipeline execution log
CREATE TABLE IF NOT EXISTS VALIDATION.PIPELINE_LOGS (
    LOG_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PIPELINE_NAME VARCHAR(255) NOT NULL,
    RUN_ID VARCHAR(255) NOT NULL,
    START_TIME TIMESTAMP_NTZ NOT NULL,
    END_TIME TIMESTAMP_NTZ,
    STATUS VARCHAR(50) NOT NULL,  -- SUCCESS, FAILED, IN_PROGRESS
    ROWS_PROCESSED NUMBER,
    ROWS_FAILED NUMBER,
    ERROR_MESSAGE VARCHAR(16777216),
    EXECUTION_TIME_SECONDS NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Validation results
CREATE TABLE IF NOT EXISTS VALIDATION.VALIDATION_RESULTS (
    VALIDATION_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID VARCHAR(255) NOT NULL,
    TABLE_NAME VARCHAR(255) NOT NULL,
    CHECK_NAME VARCHAR(255) NOT NULL,
    CHECK_TYPE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,  -- PASS, FAIL, WARNING
    EXPECTED_VALUE VARCHAR(16777216),
    ACTUAL_VALUE VARCHAR(16777216),
    MESSAGE VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Data quality metrics
CREATE TABLE IF NOT EXISTS VALIDATION.DATA_QUALITY_METRICS (
    METRIC_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID VARCHAR(255) NOT NULL,
    TABLE_NAME VARCHAR(255) NOT NULL,
    METRIC_NAME VARCHAR(255) NOT NULL,
    METRIC_VALUE NUMBER,
    THRESHOLD_MIN NUMBER,
    THRESHOLD_MAX NUMBER,
    STATUS VARCHAR(50),  -- PASS, FAIL
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_PIPELINE_LOGS_RUN_ID ON VALIDATION.PIPELINE_LOGS(RUN_ID);
CREATE INDEX IF NOT EXISTS IDX_PIPELINE_LOGS_STATUS ON VALIDATION.PIPELINE_LOGS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_VALIDATION_RESULTS_RUN_ID ON VALIDATION.VALIDATION_RESULTS(RUN_ID);
CREATE INDEX IF NOT EXISTS IDX_VALIDATION_RESULTS_STATUS ON VALIDATION.VALIDATION_RESULTS(STATUS);

-- Grant privileges
GRANT SELECT, INSERT, UPDATE ON VALIDATION.PIPELINE_LOGS TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE ON VALIDATION.VALIDATION_RESULTS TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE ON VALIDATION.DATA_QUALITY_METRICS TO ROLE PUBLIC;

-- Show tables
SHOW TABLES IN SCHEMA VALIDATION;

